---
title: An R Markdown document converted from "09_Proxies.ipynb"
output: html_document
---

# Finding proxies of top concordant/discordant SNPs

```{r}
library(readr)
library(dplyr, warn.conflicts = FALSE)
library(tidyr, warn.conflicts = FALSE)
```

```{r}
ctgwas_sig <- read_tsv("../data/ctgwas_sig.tsv", show_col_types = FALSE)
```

```{r}
head(ctgwas_sig)
```

Files to write PLINK output:

```{r}
out <- "../data/rsids"
targetsname <- paste0(out, ".targets")
outname <- paste0(out, ".targets.ld")
```

SNPs to query:

```{r}
utils::write.table(unique(ctgwas_sig$rsid), 
                   file=targetsname,
                   row=FALSE, col=FALSE, qu=FALSE)
```

PLINK command:

```{r}
cmd <- paste(
    "~/bin/plink",
    "--bfile", "~/projects/DVA/Data/ReferenceData/1kg_ref/EUR",
    "--r2", "in-phase", "with-freqs",
    "--ld-snp-list", targetsname, 
    "--ld-window-kb", 250,
    "--ld-window-r2", 0.8,
    "--ld-window", 999999,
    "--out", targetsname
)
```

Running PLINK command:

```{r}
system(cmd)
```

Proxies table:

```{r}
proxiestab <- readr::read_table(
    outname,
    skip = 1,
    col_types = "--c---ccnn-",
    col_names = c("rsid", "rsid_proxy", "phase", "maf_proxy", "r2")
)
head(proxiestab)
```

Cleaning proxies tab:

```{r}
proxiestab <- proxiestab %>%
    mutate(phase = gsub("/", "", phase)) %>%
    filter(nchar(phase) == 4) %>%
    separate_wider_position(phase, widths = c(a1 = 1, b1 = 1, a2 = 1, b2 = 1)) %>%
    mutate(
        reference_snp = rsid == rsid_proxy,
        pal1 = b1 %in% c("A", "T") & b2 %in% c("A", "T"),
        pal2 = b1 %in% c("C", "G") & b2 %in% c("C", "G"),
        pal_ambig = (pal1 | pal2) & maf_proxy > 0.4
    ) %>%
    filter(!pal_ambig) %>%
    select(-c(pal1, pal2, pal_ambig, maf_proxy)) %>%
    arrange(rsid, desc(reference_snp), desc(r2))
head(proxiestab)
```

Aligning to the allele increasing T2D risk:

```{r}
proxiestab <- ctgwas_sig %>%
    select(rsid, ea_t2d, nea_t2d) %>%
    unique %>%
    inner_join(proxiestab, by = "rsid") %>%
    mutate(
        across(
            c(a1, a2),
            ~stringr::str_replace_all(.x, c("A" = "t", "T" = "a", "C" = "g", "G" = "c")),
            .names = "{.col}_flip"
        ),
        across(
            c(a1_flip, a2_flip),
            ~toupper(.x)
        ),
        harmon1 = case_when(ea_t2d == a1 & nea_t2d == a2 ~ 1,
                            ea_t2d == a2 & nea_t2d == a1 ~ -1,
                            TRUE ~ NaN),
        harmon2 = case_when(ea_t2d == a1_flip & nea_t2d == a2_flip ~ 1,
                            ea_t2d == a2_flip & nea_t2d == a1_flip ~ -1,
                            TRUE ~ NaN),
        harmon = coalesce(harmon1, harmon2),
        ea_proxy = ifelse(harmon == 1, b1, b2),
        nea_proxy = ifelse(harmon == 1, b2, b1)
    ) %>%
    select(-c(a1, a2, a1_flip, a2_flip, b1, b2, harmon, harmon1, harmon2))
head(proxiestab)
```

Saving:

```{r}
write_tsv(proxiestab, "../data/proxiestab.tsv")
```

